CREATE TABLE PRODUCTS
  (
    PRODUCT_ID NUMBER(4,0),
    NAME_P     VARCHAR2(20 BYTE) NOT NULL,
    RATING_P   NUMBER(2,0),
    PRICE      NUMBER(12,2),
    CONSTRAINT product_id_pk PRIMARY KEY (product_id),
    CONSTRAINT products_raiting_p_ck CHECK ((RATING_P>0)
  AND (RATING_P                                     <=5))
  );
INSERT INTO PRODUCTS VALUES
  (1, 'Computer',5,1200
  );
INSERT INTO PRODUCTS VALUES
  (2, 'Monoblok',5,1400
  );
INSERT INTO PRODUCTS VALUES
  (3, 'Notebook',5,1350
  );
INSERT INTO PRODUCTS VALUES
  (4, 'Tablet',4,900
  );
INSERT INTO PRODUCTS VALUES
  (5, 'Smartphone',4,700
  );
INSERT INTO PRODUCTS VALUES
  (6, 'Printer',3,400
  );
INSERT INTO PRODUCTS VALUES
  (7, 'Scanner',3,450
  );
INSERT INTO PRODUCTS VALUES
  (8, 'Camera',2,650
  );
INSERT INTO PRODUCTS VALUES
  (9, 'Phone',2,550
  );
INSERT INTO PRODUCTS VALUES
  (10, 'Keyboard',1,30
  );
INSERT INTO PRODUCTS VALUES
  (11, 'Mouse',1,15
  );
ALTER SESSION SET NLS_DATE_LANGUAGE='AMERICAN';
ALTER SESSION SET NLS_DATE_FORMAT  ='dd-mon-yyyy';
CREATE TABLE SALES
  (
    SALES_ID NUMBER(4,0),
    SALES_DATE DATE DEFAULT SYSDATE,
    QUANTITY    NUMBER(4,0) NOT NULL,
    PRODUCT_ID  NUMBER(4,0),
    EMPLOYEE_ID NUMBER(6,0),
    CONSTRAINT sales_id_pk PRIMARY KEY (SALES_ID),
    CONSTRAINT sales_product_id_fk FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    CONSTRAINT sales_employee_id_fk FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
  );
ALTER TABLE EMPLOYEES ADD RATING_E NUMBER;
BEGIN
  FOR I IN 100..206
  LOOP
    UPDATE EMPLOYEES
    SET RATING_E =
      (SELECT ROUND(ABS(dbms_random.random/1000000000)*2 +1) FROM dual
      )
    WHERE EMPLOYEE_ID = i;
  END LOOP;
END; 